src/entry.ts
Because the function names can now be minified to single characters, this results in significant bundle size savings (17.5% minified, 5.7% after gzip) and a modest performance improvement.
Making all `Entry` properties public (so that they can be consumed by external functions) is not a problem because the entire `Entry` class is a private API of the `optimism` package.
=> Rewrite Entry class to use private functions instead of private methods.

src/entry.ts, src/tests/api.ts, src/tests/exceptions.ts, src/tests/main.ts
Previously, if a wrapped function threw an exception, no result would be cached, and the function would be recomputed the next time its wrapper was called, even if nothing upon which it depended had changed.
One of the goals of this library is to work equally well with `Promise` results as it does with ordinary results. Since a `Promise` can represent either an ordinary value or an exception, it seems important for the non-`Promise` behavior of this library to align with `Promise` behavior.
This means, most importantly, that we should be caching exceptions as well as ordinary results, to avoid doing unnecessary work just because the previous invocation of a cached function threw an exception.
If you call a cached function multiple times and get the same (`===`) rejected `Promise` object, …
=> Cache exceptions as well as ordinary values.

src/entry.ts, src/tests/api.ts
In PR #29, I reluctantly decided to preserve an old optimization in `recomputeIfDirty` that would preemptively recompute `entry.dirtyChildren` before calling `reallyRecompute(entry)`, and if none of the `dirtyChildren`’s values changed, we would assume the parent did not really need to be recomputed.
The presence of this optimization required extra effort when implementing dependency functions that don't have a meaningful return value. Often one would have to return an incrementing counter from these functions, just to convince the caching system that the dirtiness of the function should matter to its callers. At some level I think I always knew this optimization was not worth the added complexity, but I didn’t want to admit it.
While testing `optimism@0.10.0` within Meteor, I noticed a …
=> Remove unsafe arms-length optimization in recomputeIfDirty.

src/index.ts
The `OptimisticDependencyFunction` type is used by Apollo Client, and isn't currently showing up in the auto-generated `./lib/index.d.ts` file. This PR re-exports it from `index.ts`, so TS includes it in `index.d.ts`.
Related: https://github.com/apollographql/apollo-client/pull/5357/commits/68195a930b51bcbbe9bf7bc79a6826f761ccdb25
=> Re-export OptimisticDependencyFunction from index.ts

src/index.ts, src/tests/api.ts
This optional function takes the raw arguments passed to an `OptimisticFunctionWrapper` and simplifies/filters/reduces them down to an array of arguments sufficient to identify the cache result. This simplified array of arguments is then passed to `options.makeCacheKey` (or `defaultMakeCacheKey` if no `options.makeCacheKey` was provided).
The resulting array serves as the arguments list for any function that only needs to compute a cache key (and thus does not need the full raw arguments), such as `wrapper.dirty` and `options.makeCacheKey`. This makes it possible to `dirty` a cached function using less information than would be required to call it properly, which is useful in some cases.
In some sense, `options.keyArgs` and `options.makeCacheKey` divide up the work of computing cache keys …
=> Support options.keyArgs to complement options.makeCacheKey.

src/entry.ts, src/index.ts, src/tests/api.ts
Peeking cached values can be useful when you want to know if a given result is still the freshest/latest value, so you can (for example) avoid unnecessary processing that would likely just produce the same result again.
Like the `dirty` method, `peek` takes the `TKeyArgs` arguments type produced by `options.keyArgs`, if provided.
=> Allow peeking cached values without recomputing them.

src/index.ts, src/tests/api.ts
This method takes the same arguments as `optimistic.dirty` and `optimistic.peek` (`TKeyArgs`, as opposed to the full `TArgs` that the `optimistic` function itself takes). This distinction means you can remove entries as long as you have `TKeyArgs`, even if you don't have `TArgs`.
Like `Map.prototype.delete` and friends, `optimistic.forget` returns a boolean to indicate whether an entry was deleted.
This new API should enable a straightforward solution for https://github.com/apollographql/apollo-client/issues/7149 and https://github.com/apollographql/apollo-client/issues/7086.
=> Support optimistic.forget to remove Entry objects from Cache.

src/entry.ts, src/index.ts
Pretty much any kind of memoization library will create new opportunities for memory leaks, and Optimism is a memoization library.
However, as a general rule, such libraries can reduce the frequency and/or impact of memory leaks by retaining references to fewer objects internally. In some happy cases, this reduction involves eliminating long-lived references when the same data can be provided at the right times simply by passing arguments to functions.
For example, retaining a reference to the `entry.args` array made it easier in theory to recompute any `Entry` at any time. In practice, all the code that consumes `entry.args` is called as part of `Entry#recompute`, an internal method that is only ever called from optimistic wrapper functions, which always have convenient access to the …
=> Avoid storing entry.args by passing args to Entry#recompute instead.

src/index.ts
While debugging without source maps, I noticed that the default `keyArgs` function (which is used any time `options.keyArgs` is not provided, which is _most_ of the time) was relatively costly, because it had to convert its `arguments` into a proper `Array`, thanks to TypeScript's compilation of `...args` syntax.
Since this code runs every time we access the cache, even when the cache is warm, it's important for it to be as fast as possible. Luckily, instead of using a default `keyArgs` function, we can skip calling `keyArgs` altogether, which is almost certainly faster.
=> Skip turning arguments into array if options.keyArgs not provided.

src/index.ts, src/tests/api.ts
Per the conversation in https://github.com/apollographql/apollo-feature-requests/issues/289, add `getKey` & `forgetKey` API's to `OptimisticWrapperFunction`.
The motive here is to keep track of the cached entries without having to memoize the arguments and duplicate the logic for weakly tracking them. This will enable the creators of `OptimisticWrapperFunction` to use the _true_ keys for removing entries via the `forgetKey` API.
=> add getKey and forgetKey API (#188)

src/dep.ts, src/entry.ts, src/helpers.ts, src/index.ts
This improvement to the `dep.dirty` API allows invalidating the `Entry` graph in more flexible/drastic ways.
Specifically, a cached function can call `someDep(key)` during its initial computation to register an atomic dependency (as before), and then later calling `someDep.dirty(key, "forget")` will cause the parent `Entry` to be completely removed from the computation graph. This removal is more drastic than just dirtying the `Entry` with `entry.setDirty()` (which is the default/current behavior of `someDep.dirty(key)`) because it release all memory associated with the `Entry` and requires it to be recreated if it's ever needed again.
@SofianHn I think this functionality is most of what's needed to implement the second half of your original PR …
=> Allow dep.dirty to invoke Entry methods other than setDirty

package-lock.json, package.json
Apollo Client depends on `@wry/context` `^0.7.0` and on `optimism` `^0.16.1` which pulled in 2 versions of `@wry/context` which seems unnecessary. Bumping `@wry/context` here resolves this.
=> Upgrade @wry/context to 0.7.0

src/index.ts, src/tests/api.ts
Exposing these `wrapped.options` should eliminate the need to mock the `optimism` package for Apollo Client tests, introduced by https://github.com/apollographql/apollo-client/pull/8107.
=> Expose frozen `wrap(...).options` on functions returned by `wrap`

src/dep.ts, src/entry.ts
An attempt to clear keys in `depsByKey` when all previously tracked entries are disposed.
With the caveat that we should not call `cleanup` on recompute codepath.
Fixes #497
=> Cleanup depsByKey when all dependant entries are disposed

package-lock.json, package.json
This seems to be required by our use of `"importHelpers": true` in [`tsconfig.json`](https://github.com/benjamn/optimism/blob/cd90c68ecf4a6ee4551e2d24ebb0e041b8768091/tsconfig.json#L10), though I don't think the `optimism` implementation currently imports any `tslib` helpers outside of tests.
=> Move `tslib` from `devDependencies` to `dependencies`

src/context.ts, src/index.ts, src/tests/context.ts
The drawback of `noContext` is that it censors _all_ contextual `Slot` values from the inner function's context, when the only `Slot` used by `optimism` is the `parentEntrySlot`.
The new `nonReactive` function is like `noContext`, but it censors only `parentEntrySlot`, to avoid registering dependencies while executing certain code known/suspected to contain functions `wrap`ped by `optimism`.
=> Support `nonReactive(() => ...)` to avoid encouraging the sledgehammer `noContext`

src/dep.ts, src/entry.ts
This reverts commit 884d2b67125c106ec6c7ea712b51fc5039f246a2, following advice from @vladar in https://github.com/benjamn/optimism/pull/498#issuecomment-1488285575. I don't have an immediate theory about what could have changed here, but if anyone has ideas, feel free to leave a comment below.
=> Revert "Cleanup `depsByKey` when all dependant entries are disposed" (PR #498)

rollup.config.js
Similar to these previous PRs for other packages/projects:
* https://github.com/benjamn/wryware/pull/484
* https://github.com/apollographql/apollo-client/pull/9716
=> Work around React Native / Metro refusing to load `.cjs` modules

src/dep.ts, src/entry.ts, src/helpers.ts
As @alessbell has reported in https://github.com/codesandbox/sandpack/issues/940, it appears [Sandpack](https://sandpack.codesandbox.io/) may have a transpiler bug when compiling the following code:
```ts
export const {
from: toArray = (collection: Set<any>) => {
const array: any[] = [];
collection.forEach(item => array.push(item));
return array;
},
} = Array;
```
It's understandable the combination of `export`, destructuring, renaming `from: toArray`, and a default expression would be unusual enough to have escaped testing, but this works with other transpilers, and is valid TypeScript (and should compile to equivalent valid JS).
What happens, specifically, is that `exports.toArray` never gets assigned like `exports.hasOwnProperty` and `exports.maybeUnsubscribe`, presumably because …
=> Rename `toArray` to `arrayFromSet` and simplify `export` syntax

src/context.ts, src/index.ts, src/tests/context.ts
Because Apollo Client uses the `Slot` constructor directly [here](https://github.com/apollographql/apollo-client/blob/8329f07e544d1c70a0e15c6a5ccc1d563ab72f8a/src/cache/inmemory/reactiveVars.ts#L16-L18), it needs to have a direct dependency on the `@wry/context` package in addition to depending on `optimism`, which has caused dependency version mismatches leading to duplicate installs of `@wry/context`, which can cause problems with some bundlers.
Instead, when you're already using `optimism`, you might as well import the same version of `Slot` that it uses, which is what this PR enables.
=> Re-export `Slot` so consumers need not import it from `@wry/context`

src/index.ts
Returning undefined from `makeCacheKey` is the recommended technique for efficiently opting out of caching for particular combinations of input arguments, so that possibility should be reflected in the TypeScript types for the various functions that handle keys.
=> Improve types to reflect key-making functions may return `undefined`

package-lock.json, package.json, rollup.config.js, src/entry.ts, src/index.ts, src/tests/api.ts, src/tests/test-utils.ts
Sometimes a function cached with `optimism` will be spuriously dirtied (directly or indirectly) in a way that triggers recomputation the next time the function is called. The newly computed result may be logically different from the previous result, of course, but if the two results are equivalent (or share equivalent subparts), the developer may wish to keep using (parts of) the previous result.
To take advantage of this system for reconciling cached results, pass an `options.normalizeResult` callback in the options for the `wrap` function:
```ts
// Use any deep equality test you like:
import { equal } from "@wry/equality"
const range = wrap((n: number): number[] => {
return n > 0 ? range(n - 1).concat(n - 1) : [];
}, {
normalizeResult(newer: number[], older: number[]) {
return …
```
=> Support `options.normalizeResult` callback in `wrap(fn, options)` to allow reconciling newly computed results with previous results
